
export const GET_PLACE_BY_ADDRESS = 'GET_PLACE_BY_ADDRESS';
export const SHOW_DRAWING_TOOLS = 'SHOW_DRAWING_TOOLS';
export const SET_FORM_VALUES = 'SET_FORM_VALUES';
export const SEARCH_WITHIN_TIME = 'SEARCH_WITHIN_TIME';
export const NEARBY_PLACES_SEARCH = 'NEARBY_PLACES_SEARCH';
export const SET_MARKERS = 'SET_MARKERS';
export const SET_MAP = 'SET_MAP';





