export const GET_GOOGLE_API = 'GET_GOOGLE_API';
export const CREATE_MAP = 'CREATE_MAP';
export const GET_PLACE_BY_ADDRESS = 'GET_PLACE_BY_ADDRESS';
export const CREATE_MARKER = 'CREATE_MARKER';
export const CREATE_INFOWINDOW = 'CREATE_INFOWINDOW';
export const INITIALIZE_DRAWING_MANAGER = 'INITIALIZE_DRAWING_MANAGER';
export const DRAW_POLYGON = 'DRAW_POLYGON';
export const SHOW_DRAWING_TOOLS = 'SHOW_DRAWING_TOOLS';




